---
title: "Regression Analysis on VW Cars Data"
output: github_document
---

```{r setup, include=FALSE}
# Load necessary libraries
library(ggplot2)
library(leaps)
```

## Data Preparation

```{r}
# Read the dataset
vwcars <- ("../data/vwscars.csv", sep = ",")

# Create new columns for log price, fuel consumption, and age of the car
vwcars$logprice <- log(vwcars$price)
vwcars$lp100 <- 282.48 / vwcars$mpg
vwcars$age <- as.numeric(format(Sys.Date(), "%Y")) - vwcars$year

```
**Linear Regression**
```{r}
# Linear regression analysis for price
lm_price <- lm(price ~ model + age + lp100 + fuelType + engineSize + tax + transmission + mileage, data = vwcars)
summary(lm_price)

# Linear regression analysis for log(price)
lm_logprice <- lm(logprice ~ model + age + lp100 + fuelType + engineSize + tax + transmission + mileage, data = vwcars)
summary(lm_logprice)

```
**Best Subset Selection**
```{r}
# Best Subset Selection for all the subsets of the predictors
best_subsets <- regsubsets(logprice ~ model + age + lp100 + fuelType + engineSize + tax + transmission + mileage, data = vwcars, nvmax = NULL)

# Create a summary object
subsets_summary <- summary(best_subsets)

# Find the model with the lowest AIC and BIC
aic_values <- sapply(1:length(subsets_summary$outmat), function(i) {
  predictors <- names(which(subsets_summary$which[i, -1]))
  formula <- as.formula(paste("logprice ~", paste(predictors, collapse = " + ")))
  fit <- lm(formula, data = vwcars)
  AIC(fit)
})

bic_values <- sapply(1:length(subsets_summary$outmat), function(i) {
  predictors <- names(which(subsets_summary$which[i, -1]))
  formula <- as.formula(paste("logprice ~", paste(predictors, collapse = " + ")))
  fit <- lm(formula, data = vwcars)
  BIC(fit)
})

# Find the index of the minimum AIC and BIC
idx_AIC <- which.min(aic_values)
idx_BIC <- which.min(bic_values)

# Extract the variables from the best models
variables_in_aic <- names(which(subsets_summary$which[idx_AIC, ]))
variables_in_bic <- names(which(subsets_summary$which[idx_BIC, ]))

# Print AIC and BIC
AIC <- aic_values[idx_AIC]
BIC <- bic_values[idx_BIC]

cat("Best AIC model variables:", variables_in_aic, "\n")
cat("Best BIC model variables:", variables_in_bic, "\n")

# Estimate the "best" linear model for logprice using the BIC
best_formula_bic <- as.formula(paste("logprice ~", paste(variables_in_bic[-1], collapse = " + ")))
lm_bic <- lm(best_formula_bic, data = vwcars)
summary(lm_bic)
confint(lm_bic)

```
## Assumptions Checking
**Residual vs Fitted Plot**
```{r}
ggplot(vwcars, aes(y = lm_bic$residuals, x = lm_bic$fitted.values)) +
  geom_point() +
  ylab("Residuals") +
  xlab("Fitted values") +
  ggtitle("Residual vs Fitted Plot") +
  theme(plot.title = element_text(size = 20, hjust = 0.5, face = "bold"), text = element_text(size = 20)) +
  geom_abline(intercept = 0, slope = 0, col = "blue") +
  theme_bw()

```
**Scale-Location Plot**
```{r}
fitted_values <- fitted(lm_bic)
std_res <- rstandard(lm_bic)

ggplot(data = vwcars, aes(y = std_res, x = fitted_values)) +
  geom_point(size = 1.5) +
  geom_smooth(method = "lm", se = FALSE, size = 1, color = "blue") +
  ggtitle("Scale-Location Plot") +
  labs(y = "Standardized Residuals", x = "Fitted Values") +
  theme(plot.title = element_text(size = 20, hjust = 0.5, face = "bold"), text = element_text(size = 20)) +
  theme_bw()

```
**Normal Q-Q Plot**
```{r}
ggplot(data = vwcars, aes(sample = lm_bic$residuals)) +
  geom_qq(color = "black") +
  geom_qq_line(color = "blue") +
  labs(y = "Residuals (BIC model)", x = "Theoretical Quantiles (BIC model)") +
  theme_bw() +
  theme(axis.title.x = element_text(size = 14, face = "bold"),
        axis.title.y = element_text(size = 14, face = "bold"),
        axis.text = element_text(size = 12, face = "bold")) +
  theme_bw()

```